spring:
  data:
    mongodb:
      username: ${MONGODB_USERNAME:dongnv}
      password: ${MONGODB_PASSWORD:dongnv}
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB:chat_app}
      authentication-database: admin
server:
  port: 8080